/*
 * Copyright (C) 2021 Alonso del Arte
 *
 * This program is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free Software 
 * Foundation, either version 3 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package algebraics.quartics;

import algebraics.PowerBasis;
import algebraics.quadratics.QuadraticRing;
import fractions.Fraction;

/**
 * Represents a ring of algebraic integers of degree 4 which is generated by the 
 * sum of two square roots of squarefree integers. Such a ring has three 
 * intermediate quadratic rings.
 * @author Alonso del Arte
 */
public abstract class BiquadraticRing extends QuarticRing {
    
    private final QuadraticRing intermediateRingA, intermediateRingB, 
            intermediateRingC;
    
    public QuadraticRing[] getIntermediateRings() {
        QuadraticRing[] rings = {this.intermediateRingA, this.intermediateRingB, 
            this.intermediateRingC};
        return rings;
    }

    // STUB TO FAIL THE FIRST TEST
    @Override
    public int discriminant() {
        return 0;
    }
    
    // STUB TO FAIL THE TEST
    @Override
    public PowerBasis getPowerBasis() {
        Fraction zeroFract = new Fraction(0);
        Fraction[] fracts = {zeroFract, zeroFract};
        return new PowerBasis(fracts);
    }
    
    // STUB TO FAIL THE FIRST TEST
    @Override
    public String toASCIIString() {
        return "Not implemented yet";
    }

    // STUB TO FAIL THE FIRST TEST
    @Override
    public String toTeXString() {
        return "Not implemented yet";
    }

    // STUB TO FAIL THE FIRST TEST
    @Override
    public String toHTMLString() {
        return "Not implemented yet";
    }

    // STUB TO FAIL THE FIRST TEST
    @Override
    public String toFilenameString() {
        return "Not implemented yet";
    }
    
    public BiquadraticRing(QuadraticRing ringA, QuadraticRing ringB, 
            QuadraticRing ringC) {
        this.intermediateRingA = ringA;
        this.intermediateRingB = ringB;
        this.intermediateRingC = ringC;
    }
    
}
